### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by gFulvio** [srcnalt/RPM-Smart-NPC#7]
I tried to open the project but I got this error message:
Assets\Scripts\TextToSpeech.cs(17,51): error CS0103: The name 'Credentials' does not exist in the current context

**Comment by srcnalt** [comment]
Hi @gFulvio you can create the class to keep your credentials in it or hardcode it in the code yourself.

**Comment by gFulvio** [comment]
I think I will have to watch your text-to-speech video to understand better. Thank you! I love your job!

**Comment by srcnalt** [comment]
yes that should help.

the file should look like this, it just hides 2 fields which are private info you should not expose incase someone else uses them.

```cs
public class Credentials {
  public static string ACCESS_KEY = "your aws access key";
  public static string SECRET_KEY = "your aws secret key";
}
```
